[build]
  command = """
    mkdir -p dist && \
    for dir in ./*/; do \
      if [ -f "$dir/package.json" ]; then \
        project=$(basename "$dir"); \
        echo "🛠️ Building $project"; \
        cd "$dir" && npm install && \
        NUXT_APP_BASE_URL="/$project/" npx nuxt build --preset netlify && \
        cd .. && \
        mkdir -p "dist/$project" && \
        cp -r "$dir/.output/public/"* "dist/$project/"; \
      fi \
    done
  """
  publish = "dist"

[build.environment]
  NITRO_PRESET = "netlify"
  NODE_VERSION = "20"